---
timing:
  tweets: 5.0
  backgrounds: 0.5

twitter:
  username: Inukshuk2012
  password: kuhskuni

oauth:
  consumer_key: 'I65uR1aubSVsDh2qDS75g'
  consumer_secret: 'jUJtNVOzng3DCaGmjYsp4yKcVAQ8wfN80SY6gUUOoM'
  access_token: '7892772-wryXcKce7x36EJvHrDLdQnrxVJqB1v53U0AVmQJIeQ'
  access_token_secret: 'KbsZ3Yuo1SU9EjmUWTq4LPIwqEi2AnHsEBIf9yJUJ0E'

arduino:
  host: "192.168.15.15"
  port: 21
